CREATE DATABASE gitpushforce_db

use gitpushforce_db

CREATE TABLE Users(
    CNP VARCHAR(16) PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(255),
    HashedPassword VARCHAR(255),
    NoOffenses INT,
    RiskScore INT,
    ROI INT,
    CreditScore INT,
    Birthday DATE,
    ZodiacSign VARCHAR(255),
    ZodiacAttribute VARCHAR(255)
);

CREATE TABLE ChatReports(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ReportedUserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_CHATREPORT_USER FOREIGN KEY (ReportedUserCNP) REFERENCES Users(CNP),
    ReportedMessage VARCHAR(255),
    Status VARCHAR(255)
)

CREATE TABLE ActivityLog(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    Name VARCHAR(255) NOT NULL,
    UserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_ACTIVITYLOG_USER FOREIGN KEY (UserCNP) REFERENCES Users(CNP),
    LastModifiedAmount INT NOT NULL,
    Details VARCHAR(255)
)

CREATE TABLE Investments(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    UserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_INVESTMENTS_USER FOREIGN KEY (UserCNP) REFERENCES Users(CNP),
    Details VARCHAR(255),
    Type VARCHAR(255) NOT NULL,
    AmountInvested DECIMAL(6, 2) NOT NULL,
    Income DECIMAL(6, 2) NOT NULL
)

CREATE TABLE BillSplitReports(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ReportedUserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_BILLSPLIT_USERREPORTED FOREIGN KEY (ReportedUserCNP) REFERENCES Users(CNP),
    ReporterUserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_BILLSPLIT_USERREPORTER FOREIGN KEY (ReporterUserCNP) REFERENCES Users(CNP),
    DateOfTransaction DATE NOT NULL,
    BillShare DECIMAL(6, 2) NOT NULL,
    GravityFactor DECIMAL(6, 2) NOT NULL
)

CREATE TABLE CreditScoreHistory(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    UserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_CREDITSCOREHISTORY_USERS FOREIGN KEY (UserCNP) REFERENCES Users(CNP),
    Date DATE NOT NULL,
    Score INT,
)

CREATE TABLE Tips(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    CreditScoreBracket VARCHAR(255),
    TipText VARCHAR(255) NOT NULL
)

CREATE TABLE Messages(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    Type VARCHAR(16),
    Message VARCHAR(255)
)

CREATE TABLE GivenTips(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    UserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_GIVENTIPS_USERS FOREIGN KEY (UserCNP) REFERENCES Users(CNP),
    TipID INT,
    CONSTRAINT FK_GIVENTIPS_TIPS FOREIGN KEY (TipID) REFERENCES Tips(ID),
    MessageID INT,
    CONSTRAINT FK_GIVENTIPS_MESSAGES FOREIGN KEY (MessageID) REFERENCES Messages(ID),
    Date DATE NOT NULL
)

CREATE TABLE Loans(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    UserCNP VARCHAR(16) NOT NULL,
    CONSTRAINT FK_LOANS_USERS FOREIGN KEY (UserCNP) REFERENCES Users(CNP),
    Amount DECIMAL(6, 2) NOT NULL,
    Currency VARCHAR(255),
    DateTaken DATE NOT NULL,
    DateDeadline DATE NOT NULL,
    DatePaid DATE,
    InterestRate DECIMAL(6, 2) NOT NULL,
    NoMonths INT NOT NULL,
    State VARCHAR(255) NOT NULL
)